In [32]:
from d6_diagonal_optimizer import build_optimized_circuit
import numpy as np
omega3 = np.exp(2j * np.pi / 3)
omega3_bar = np.conj(omega3)

In [33]:
diag46 = np.array(
        [
            1, omega3_bar, omega3_bar, omega3_bar, omega3_bar, 1,
            1, 1, omega3, 1, omega3, 1,
            1, omega3, 1, omega3, 1, 1,
            1, omega3, 1, omega3_bar, omega3, omega3_bar,
            omega3_bar, omega3, omega3, omega3_bar, 1, 1,
            omega3, omega3, omega3_bar, 1, 1, omega3_bar,
        ],
        dtype=complex,
    )

In [34]:
qc_opti = build_optimized_circuit(diag46)

In [35]:
qc_opti.depth()

107

In [36]:
from qiskit.quantum_info import Operator, Statevector

In [37]:
np.diag(Operator(qc_opti).data.round(3))

array([ 1. +0.j   , -0.5-0.866j, -0.5-0.866j, -0.5-0.866j, -0.5-0.866j,
        1. -0.j   ,  1. -0.j   ,  1. +0.j   ,  1. +0.j   ,  1. -0.j   ,
       -0.5+0.866j,  1. +0.j   , -0.5+0.866j,  1. +0.j   ,  1. +0.j   ,
        1. +0.j   ,  1. +0.j   , -0.5+0.866j,  1. +0.j   , -0.5+0.866j,
        1. -0.j   ,  1. +0.j   ,  1. +0.j   ,  1. +0.j   ,  1. +0.j   ,
       -0.5+0.866j,  1. -0.j   , -0.5-0.866j, -0.5+0.866j, -0.5-0.866j,
        1. +0.j   ,  1. +0.j   , -0.5-0.866j, -0.5+0.866j, -0.5+0.866j,
       -0.5-0.866j,  1. -0.j   ,  1. -0.j   ,  1. +0.j   ,  1. -0.j   ,
       -0.5+0.866j, -0.5+0.866j, -0.5-0.866j,  1. +0.j   ,  1. +0.j   ,
       -0.5-0.866j,  1. +0.j   ,  1. -0.j   ,  1. -0.j   ,  1. +0.j   ,
        1. -0.j   ,  1. +0.j   ,  1. -0.j   ,  1. +0.j   ,  1. +0.j   ,
        1. +0.j   ,  1. +0.j   ,  1. +0.j   ,  1. +0.j   ,  1. -0.j   ,
        1. -0.j   ,  1. -0.j   ,  1. -0.j   ,  1. +0.j   ])

In [38]:
omega3, omega3_bar

(np.complex128(-0.4999999999999998+0.8660254037844387j),
 np.complex128(-0.4999999999999998-0.8660254037844387j))

In [39]:
def counttwoqgates(qc):
    two_q_gates = 0

    for i in qc.data:
        if len(i.qubits) == 2:
            two_q_gates += 1

    return two_q_gates

In [40]:
from qiskit.circuit.library import DiagonalGate, UnitaryGate

In [41]:
from qiskit.circuit import Parameter
from qiskit import QuantumCircuit
from math import pi

In [42]:
# obwod z pracy, figure 11.
qc = QuantumCircuit(6, name="diag_AME_4_6")

# a_j odpowiada alfa_j z rysunku
a = {j: Parameter(f"a{j}") for j in range(1, 7)}

def rz(j, q, sign=1):
    qc.rz(sign * a[j], q)

def cx(control, target):
    qc.cx(control, target)


# ===== fragment 1 =====
rz(1, 0, -1)
cx(1, 0)
rz(3, 0, -1)
cx(2, 0)
rz(1, 0, +1)
cx(1, 0)
rz(1, 0, -1)
cx(3, 0)
rz(3, 0, +1)
cx(1, 0)
rz(3, 0, -1)
cx(2, 0)
rz(1, 0, -1)
cx(1, 0)
rz(1, 0, -1)
cx(4, 0)
rz(1, 0, +1)
cx(1, 0)
rz(3, 0, +1)
cx(2, 0)
rz(3, 0, +1)
cx(1, 0)
rz(1, 0, -1)
cx(3, 0)
rz(5, 0, -1)


# ===== fragment 2 =====
cx(1, 0)
rz(1, 0, -1)
cx(2, 0)
rz(1, 0, -1)
cx(1, 0)
rz(1, 0, +1)
cx(5, 0)
rz(1, 0, +1)
cx(1, 0)
rz(3, 0, -1)
cx(2, 0)
rz(3, 0, -1)
cx(1, 0)
rz(5, 0, -1)
cx(3, 0)
rz(1, 0, -1)
cx(1, 0)
rz(1, 0, +1)
cx(2, 0)
rz(1, 0, -1)
cx(1, 0)
rz(1, 0, +1)
cx(4, 0)
rz(1, 0, -1)
cx(1, 0)
rz(3, 0, -1)


# ===== fragment 3 =====
cx(2, 0)
rz(5, 0, -1)
cx(1, 0)
rz(3, 0, +1)
cx(3, 0)
rz(1, 0, -1)
cx(1, 0)
rz(1, 0, -1)
cx(2, 0)
rz(1, 0, +1)
cx(1, 0)
rz(1, 0, -1)

rz(2, 1, +1)
cx(2, 1)
cx(5, 0)

rz(2, 1, -1)
cx(3, 1)
cx(2, 1)
cx(4, 1)
cx(2, 1)

rz(2, 1, -1)
cx(3, 1)
cx(2, 1)

rz(2, 1, -1)
cx(5, 1)

rz(2, 1, -1)
cx(2, 1)
cx(3, 1)

rz(2, 1, -1)


# ===== fragment 4 =====
cx(2, 1)
cx(4, 1)
cx(2, 1)
cx(3, 1)

rz(2, 1, -1)
cx(2, 1)

rz(2, 1, +1)
rz(2, 2, +1)

cx(3, 2)
cx(4, 2)

rz(4, 2, +1)
cx(5, 1)
cx(3, 2)

rz(2, 2, +1)
cx(5, 2)
cx(3, 2)

rz(2, 2, +1)
cx(4, 2)

rz(2, 2, -1)
cx(3, 2)

rz(6, 3, +1)
cx(5, 2)
cx(4, 3)

rz(4, 3, +1)
cx(5, 3)

rz(2, 3, +1)
cx(4, 3)

rz(4, 3, +1)
rz(2, 4, +1)

cx(5, 3)
rz(2, 5, +1)


# Podstawienie wartości z podpisu: alpha_j = j*pi/24
bindings = {a[j]: j * pi / 24 for j in range(1, 7)}

qc_bound = qc.assign_parameters(bindings, inplace=False)

In [43]:
len(Operator(qc_bound).data.round(3))

64

In [ ]:
# obwod ktory uwzglednia zabronione stany w srodku diagonali
diagqc = np.diag(Operator(qc_opti).data.round(3))
idx = np.array([0,1,2,3,4,5,8,9,10,11,12,13,16,17,18,19,20,21,24,25,26,27,28,29,32,33,34,35,36,37,40,41,42,43,44,45])
# invalid idx to sa indexy dla ktorych musimy miec 1 bo odpowiadaja one stanom zabronionym
idx_invalid = np.array([6,7,14,15,22,23,30,31,38,39,46,47,48] + [i for i in range(49,64)])
idx_invalid
diagqc[idx_invalid], len(diagqc[idx_invalid])

(array([1.-0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j,
        1.+0.j, 1.-0.j, 1.+0.j, 1.-0.j, 1.-0.j, 1.+0.j, 1.-0.j, 1.+0.j,
        1.-0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.-0.j,
        1.-0.j, 1.-0.j, 1.-0.j, 1.+0.j]),
 28)

In [45]:
[i for i in range(49,64)]

[49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]

In [46]:
import numpy as np
from itertools import product

In [47]:
import numpy as np

from qiskit import QuantumCircuit, transpile
from qiskit.circuit.library import Diagonal
from qiskit.quantum_info import Operator


# ============================================================
# Lambda_{2,3}
#
#  0  -> phase 0             -> exp(i*0)       = 1
#  1  -> phase +2*pi/3       -> exp(+2pi i/3)  = omega
# -1  -> phase -2*pi/3       -> exp(-2pi i/3)  = conj(omega)
# ============================================================

lambda_units_36 = np.array([
     0, -1, -1, -1, -1,  0,
     0,  0,  1,  0,  1,  0,
     0,  1,  0,  1,  0,  0,
     0,  1,  0, -1,  1, -1,
    -1,  1,  1, -1,  0,  0,
     1,  1, -1,  0,  0, -1
], dtype=float)

# Tak jak w notebooku: 36 faz + 28 zerowych faz
lambda_units_64 = np.concatenate([
    lambda_units_36,
    np.zeros(28)
])

Lambda = (2 * np.pi / 3) * lambda_units_64
diagonal_elements = np.exp(1j * Lambda)

n_qubits = 6
dim = 2 ** n_qubits

U_target = np.diag(diagonal_elements)


# ============================================================
# Tworzymy bramkę diagonalną
# ============================================================

qc_diag = QuantumCircuit(n_qubits, name="D_Lambda_2_3")

diag_gate = Diagonal(diagonal_elements)
qc_diag.append(diag_gate, list(range(n_qubits)))


# ============================================================
# Krok 1: Qiskit niech rozłoży Diagonal do u + cx
# ============================================================

qc_ucx = transpile(
    qc_diag,
    basis_gates=["u", "cx"],
    optimization_level=3
)

print("Po transpilacji do u+cx:")
print(qc_ucx.count_ops())


# ============================================================
# Krok 2: Zamieniamy fazowe u na rz
#
# Qiskit:
# u(0, phi, lambda) = diag(1, exp(i(phi+lambda)))
#
# Z kolei:
# rz(theta) = diag(exp(-i theta/2), exp(i theta/2))
#
# Więc:
# u(0, phi, lambda) = global_phase * rz(phi + lambda)
# ============================================================

def convert_phase_u_to_rz_cx(circuit, atol=1e-9):
    out = QuantumCircuit(circuit.num_qubits, circuit.num_clbits)
    out.global_phase = circuit.global_phase

    for item in circuit.data:
        inst = item.operation
        qargs = [circuit.find_bit(q).index for q in item.qubits]
        cargs = [circuit.find_bit(c).index for c in item.clbits]

        if inst.name == "cx":
            out.cx(qargs[0], qargs[1])

        elif inst.name == "rz":
            theta = float(inst.params[0])
            out.rz(theta, qargs[0])

        elif inst.name == "u":
            theta = float(inst.params[0])
            phi = float(inst.params[1])
            lam = float(inst.params[2])

            # Bramka u jest fazowa wtedy, gdy sin(theta/2) = 0,
            # czyli theta = 0 mod 2pi.
            if not np.isclose(np.sin(theta / 2), 0.0, atol=atol):
                raise ValueError(
                    f"Nie da się zamienić tej bramki u na samo rz: "
                    f"u({theta}, {phi}, {lam})"
                )

            gamma = phi + lam

            # Jeśli cos(theta/2) = -1, dochodzi dodatkowa globalna faza pi.
            if np.cos(theta / 2) < 0:
                out.global_phase += np.pi

            out.global_phase += gamma / 2
            out.rz(gamma, qargs[0])

        elif inst.name == "barrier":
            out.barrier(*qargs)

        else:
            raise ValueError(f"Nieobsługiwana bramka: {inst.name}")

    return out


qc_rzcx = convert_phase_u_to_rz_cx(qc_ucx)

print()
print("Po konwersji do rz+cx:")
print(qc_rzcx.count_ops())
print("Depth:", qc_rzcx.depth())


# ============================================================
# Sprawdzenie zgodności z targetem
# ============================================================

U_circuit = Operator(qc_rzcx).data

overlap = np.abs(np.trace(U_circuit.conj().T @ U_target))
trace_fidelity = overlap / dim

avg_gate_fidelity = (
    np.abs(np.trace(U_target.conj().T @ U_circuit)) ** 2 + dim
) / (dim * (dim + 1))

print()
print("=== Fidelity ===")
print("Trace fidelity:", trace_fidelity)
print("Average gate fidelity:", avg_gate_fidelity)

print()
print("Czy zgadza się z targetem z dokładnością numeryczną?")
print(np.allclose(U_circuit, U_target, atol=1e-8))

Po transpilacji do u+cx:
OrderedDict({'cx': 56, 'u': 51})

Po konwersji do rz+cx:
OrderedDict({'cx': 56, 'rz': 51})
Depth: 101

=== Fidelity ===
Trace fidelity: 0.9999999999999984
Average gate fidelity: 0.9999999999999969

Czy zgadza się z targetem z dokładnością numeryczną?
True


C:\Users\szymo\AppData\Local\Temp\ipykernel_7072\1358207430.py:46: DeprecationWarning: The class ``qiskit.circuit.library.generalized_gates.diagonal.Diagonal`` is deprecated as of Qiskit 2.1. It will be removed in Qiskit 3.0. Use DiagonalGate instead.
  diag_gate = Diagonal(diagonal_elements)


In [48]:
np.diag(Operator(qc_rzcx).data).round(3)

array([ 1. -0.j   , -0.5-0.866j, -0.5-0.866j, -0.5-0.866j, -0.5-0.866j,
        1. -0.j   ,  1. -0.j   ,  1. +0.j   , -0.5+0.866j,  1. +0.j   ,
       -0.5+0.866j,  1. +0.j   ,  1. +0.j   , -0.5+0.866j,  1. +0.j   ,
       -0.5+0.866j,  1. +0.j   ,  1. -0.j   ,  1. +0.j   , -0.5+0.866j,
        1. -0.j   , -0.5-0.866j, -0.5+0.866j, -0.5-0.866j, -0.5-0.866j,
       -0.5+0.866j, -0.5+0.866j, -0.5-0.866j,  1. -0.j   ,  1. -0.j   ,
       -0.5+0.866j, -0.5+0.866j, -0.5-0.866j,  1. +0.j   ,  1. -0.j   ,
       -0.5-0.866j,  1. +0.j   ,  1. +0.j   ,  1. -0.j   ,  1. +0.j   ,
        1. +0.j   ,  1. -0.j   ,  1. +0.j   ,  1. +0.j   ,  1. +0.j   ,
        1. +0.j   ,  1. +0.j   ,  1. +0.j   ,  1. -0.j   ,  1. +0.j   ,
        1. +0.j   ,  1. +0.j   ,  1. +0.j   ,  1. +0.j   ,  1. +0.j   ,
        1. +0.j   ,  1. +0.j   ,  1. +0.j   ,  1. +0.j   ,  1. +0.j   ,
        1. +0.j   ,  1. +0.j   ,  1. +0.j   ,  1. +0.j   ])

In [49]:
np.diag(Operator(qc_opti).data).round(3)

array([ 1. +0.j   , -0.5-0.866j, -0.5-0.866j, -0.5-0.866j, -0.5-0.866j,
        1. -0.j   ,  1. -0.j   ,  1. +0.j   ,  1. +0.j   ,  1. -0.j   ,
       -0.5+0.866j,  1. +0.j   , -0.5+0.866j,  1. +0.j   ,  1. +0.j   ,
        1. +0.j   ,  1. +0.j   , -0.5+0.866j,  1. +0.j   , -0.5+0.866j,
        1. -0.j   ,  1. +0.j   ,  1. +0.j   ,  1. +0.j   ,  1. +0.j   ,
       -0.5+0.866j,  1. -0.j   , -0.5-0.866j, -0.5+0.866j, -0.5-0.866j,
        1. +0.j   ,  1. +0.j   , -0.5-0.866j, -0.5+0.866j, -0.5+0.866j,
       -0.5-0.866j,  1. -0.j   ,  1. -0.j   ,  1. +0.j   ,  1. -0.j   ,
       -0.5+0.866j, -0.5+0.866j, -0.5-0.866j,  1. +0.j   ,  1. +0.j   ,
       -0.5-0.866j,  1. +0.j   ,  1. -0.j   ,  1. -0.j   ,  1. +0.j   ,
        1. -0.j   ,  1. +0.j   ,  1. -0.j   ,  1. +0.j   ,  1. +0.j   ,
        1. +0.j   ,  1. +0.j   ,  1. +0.j   ,  1. +0.j   ,  1. -0.j   ,
        1. -0.j   ,  1. -0.j   ,  1. -0.j   ,  1. +0.j   ])

In [50]:
qc_opti.depth()

107

In [51]:
qc_rzcx.depth()

101

In [ ]:
# tutaj mamy nie tylko jedynki na "zabronionych" indeksach
diagqc = np.diag(Operator(qc_rzcx).data.round(3))
idx = np.array([0,1,2,3,4,5,8,9,10,11,12,13,16,17,18,19,20,21,24,25,26,27,28,29,32,33,34,35,36,37,40,41,42,43,44,45])
idx_invalid = np.array([6,7,14,15,22,23,30,31,38,39,46,47,48] + [i for i in range(49,64)])
idx_invalid
diagqc[idx_invalid], len(diagqc[idx_invalid])

(array([ 1. -0.j   ,  1. +0.j   ,  1. +0.j   , -0.5+0.866j, -0.5+0.866j,
        -0.5-0.866j, -0.5+0.866j, -0.5+0.866j,  1. -0.j   ,  1. +0.j   ,
         1. +0.j   ,  1. +0.j   ,  1. -0.j   ,  1. +0.j   ,  1. +0.j   ,
         1. +0.j   ,  1. +0.j   ,  1. +0.j   ,  1. +0.j   ,  1. +0.j   ,
         1. +0.j   ,  1. +0.j   ,  1. +0.j   ,  1. +0.j   ,  1. +0.j   ,
         1. +0.j   ,  1. +0.j   ,  1. +0.j   ]),
 28)